apiVersion: v1
kind: Service
metadata:
  name: vctry-ruby-svc
  labels:
    app: vctry-ruby-deployment
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3000
    protocol: TCP
  selector:
    app: vctry-ruby-deployment