version: '3'
services:
  client-pg-db:
    image: postgres:9.5.22-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment: 
#      - DEBUG=1
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  ruby-client-web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment: 
      - REDIS_URL=redis://localhost:6379/5
      - PG_PASSWORD=postgres
      - PG_USER=postgres
      - PG_HOST=vctry_client_client-pg-db_1
      - PG_PORT=5432
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    depends_on:
      - client-pg-db
