development:
  # adapter: async
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/1") %>
# 
test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: vctry_staging

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: vctry_production
